### ISSUE TITLE
New Landing Page

### ISSUE THREAD

**Issue by AbirSantra** [AbirSantra/resumebuilder#6]
Please change the landing page design according to the new figma file.

**Comment by 0AnushkaKar1** [comment]
I would like to contribute

**Comment by AbirSantra** [comment]
@0AnushkaKar1 Start building the new landing page. All the image resources are provided in the 'images' folder under the 'src' folder. Figma link has been added to the readme.
[Figma link ](https://www.figma.com/file/pxtfrT74yYkpZ1HwHvvfCq/Resu.Me?node-id=0%3A1)

**Comment by AbirSantra** [comment]
Closing as Completed
